services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      - sep-bridge-network
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xms512m"
    volumes:
      - ./infra-config/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./infra-data/elk/data/elasticsearch:/usr/share/elasticsearch/data/

  logstash:
    image: logstash:8.13.0
    container_name: logstash
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - sep-bridge-network
    ports:
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./infra-config/elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./infra-config/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./infra-data/elk/data/logstash:/usr/share/logstash/data
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.13.0
    container_name: kibana
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - sep-bridge-network
    ports:
      - "1004:5601"
    volumes:
      - ./infra-config/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./infra-data/elk/data/kibana:/usr/share/kibana/data
    depends_on:
      - elasticsearch

networks:
  sep-bridge-network:
    name: sep-bridge-network
    external: true
