services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - sep-bridge-network
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<SERVER_URL>:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - ./infra-data/kafka/data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: "kafka-ui"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - sep-bridge-network
    ports:
      - 1005:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka

networks:
  sep-bridge-network:
    name: sep-bridge-network
    external: true
