services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - sep-bridge-network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sep_product
    volumes:
      - ./infra-data/mysql/data:/var/lib/mysql

  mysql-phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - sep-bridge-network
    ports:
      - 1001:80
    environment:
      PMA_ARBITRARY: 1
    links:
      - "mysql:db"
    depends_on:
      - mysql

networks:
  sep-bridge-network:
    name: sep-bridge-network
    external: true
