server.port: 8090

spring:
  profiles.active: dev
  application.name: sep-discovery-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance.lease-renewal-interval-in-seconds: 0
