spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<MYSQL-HOST>:3306/sep_product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Etc/GMT
    username: root
    password: "{cipher}<MYSQL-PASSWORD>"
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true

redis:
  cache-name-prefix: sep-product-service-

kafka:
  consumer:
    group-id: sep-product-group

jwt:
  client-id: sep-product-service
  client-secret: "{cipher}<KEYCLOAK-CLIENT-SECRET>"
