spring:
  data:
    mongodb:
      host: <MONGO-HOST>
      port: 27017
      database: sep_payment
      username: admin
      password: "{cipher}<MONGO-PASSWORD>"
      authentication-database: admin

kafka:
  consumer:
    group-id: sep-payment-group

jwt:
  client-id: sep-payment-service
  client-secret: "{cipher}<KEYCLOAK-CLIENT-SECRET>"
