spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

kafka:
  consumer:
    group-id: sep-search-group

jwt:
  client-id: sep-search-service
  client-secret: "{cipher}<KEYCLOAK-CLIENT-SECRET>"
