spring:
  cloud:
    gateway:
     routes:
        # Discovery Service routes
        - id: discovery-service
          uri: lb://sep-discovery-service
          predicates:
            - Path=/eureka-dashboard/**, /eureka/**

        # Product Service routes
        - id: product-service
          uri: lb://sep-product-service
          predicates:
            - Path=/products/**
          filters:
            - name: RewritePath
              args:
                regexp: /products(?<segment>.*)
                replacement: $\{segment}

        # Payment Service routes
        - id: payment-service
          uri: lb://sep-payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: RewritePath
              args:
                regexp: /payments(?<segment>.*)
                replacement: $\{segment}
        
        # Search Service routes
        - id: search-service
          uri: lb://sep-search-service
          predicates:
            - Path=/search/**
          filters:
            - name: RewritePath
              args:
                regexp: /search(?<segment>.*)
                replacement: $\{segment}

        # Aggregator Service routes
        - id: aggregator-service
          uri: lb://sep-aggregator-service
          predicates:
            - Path=/aggregator/**
          filters:
            - name: RewritePath
              args:
                regexp: /aggregator(?<segment>.*)
                replacement: $\{segment}

        # GraphiQL ui for Aggregator Service
        - id: aggregator-service-graphiql
          uri: lb://sep-aggregator-service
          predicates:
            - Path=/graphiql/**, /graphiql/**

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Gateway Service
        primaryName: API Gateway Service
      - url: /products/v3/api-docs
        name: Product Service
        primaryName: Product Service
      - url: /payments/v3/api-docs
        name: Payment Service
        primaryName: Payment Service
      - url: /search/v3/api-docs
        name: Search Service
        primaryName: Search Service

authentication-filter:
  enabled: true
